### ISSUE TITLE
Frontpage action icon readability problem

### ISSUE THREAD

**Issue by yookoala** [opensourcehk/2016.opensource.hk#10]
The bottom right corner of front page first scroll has an action button. The color is now white on yellow (with transparency). The text is not as readable as other pages.

The button on frontpage:

![screenshot from 2016-02-21 02-12-55](https://cloud.githubusercontent.com/assets/91274/13198330/ef0ecf64-d840-11e5-8e2c-fe38438b8807.png)

This is how the same button looks like on other pages:

![screenshot from 2016-02-21 02-13-21](https://cloud.githubusercontent.com/assets/91274/13198332/f3dabeb8-d840-11e5-8251-71d7b67a1a0b.png)

Suggested solution: use the exact same color scheme on both places.

Need discussion here.

**Comment by tonyhhyip** [comment]
It goes better when I use it with `font-weight: bolder`

**Comment by yookoala** [comment]
Any screen cap? (Github will support the upload. Just drag the screenshot image file into the typing area)

**Comment by yookoala** [comment]
Also. The designer in our company usually says "consistency is more important to users". That says the same thing should look the same through out the site, unless absolutely necessary to break.

Is it necessary for the button to look different on front page?

**Comment by tonyhhyip** [comment]
You may take a look on this. I am thinking about adding a pop-out window (http://getbootstrap.com/javascript/#modals) on front page for early bird ticket.
![screenshot from 2016-02-21 14 55 31](https://cloud.githubusercontent.com/assets/9844551/13201413/3ddf35ce-d8ab-11e5-80d9-6fae8339bbbb.png)

**Comment by yookoala** [comment]
Resolved by #11. Thanks @tonyhhyip
